name: Release Build

on:
  push:
    tags:
      - 'v[0-9]+.*'

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create_stable_release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
  build_stable:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    needs: create_stable_release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2020.1.3f1
        targetPlatform:
          - StandaloneOSX
          - StandaloneWindows64
          - StandaloneLinux64
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: webbertakken/unity-builder@v1.2
        with:
          customParameters: -nographics
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
      - run: zip -r build.zip build
      - uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create_stable_release.outputs.upload_url }}
          asset_name: ${{ matrix.targetPlatform }}.zip
          asset_path: build.zip
          asset_content_type: application/octet-stream
